version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: hashicorp/nomad:latest
    environment:
      IMAGE_NAME: ghcr.io/berkaydedeoglu/reverse-proxy-master
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Docker build
          command: |
            cd reverse-proxy-master
            docker build -t $IMAGE_NAME:latest .

      - run:
          name: Docker login to GHCR
          command: echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USER --password-stdin

      - run:
          name: Docker push
          command: docker push $IMAGE_NAME:latest

      - run:
          name: Convert Nomad job to JSON
          command: |
            nomad job parse -json reverse-proxy-master/reverse-proxy-master.nomad > job.json

      - run:
          name: Deploy to Nomad via API
          command: |
            curl -X POST "$NOMAD_ADDR/v1/jobs" \
              -H "Content-Type: application/json" \
              --data-binary @job.json

workflows:
  version: 2
  deploy:
    jobs:
      - build-and-deploy
