version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_NAME: ghcr.io/berkaydedeoglu/reverse-proxy-master

  deploy-executor:
    docker:
      - image: curlimages/curl:latest  # sadece curl ile deploy

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Docker build
          command: |
            cd reverse-proxy-master
            docker build -t $IMAGE_NAME:latest .

      - run:
          name: Docker login
          command: echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USER --password-stdin

      - run:
          name: Docker push
          command: docker push $IMAGE_NAME:latest

  deploy-nomad:
    executor: deploy-executor
    steps:
      - checkout

      - run:
          name: Deploy HCL to Nomad API
          command: |
            curl -X POST "$NOMAD_ADDR/v1/jobs/parse?region=global&canonicalize=true&validate=true" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @reverse-proxy-master/reverse-proxy-master.nomad \
              | tee response.json

            echo "Posting parsed job to /v1/jobs..."
            curl -X POST "$NOMAD_ADDR/v1/jobs" \
              -H "Content-Type: application/json" \
              --data-binary @response.json

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push
      - deploy-nomad:
          requires:
            - build-and-push
