version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_NAME: ghcr.io/berkaydedeoglu/reverse-proxy-master

  deploy-executor:
    docker:
      - image: alpine:latest
    environment:
      NOMAD_JOB_FILE: reverse-proxy-master/reverse-proxy-master.nomad
    working_directory: ~/project

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Docker build
          command: |
            cd reverse-proxy-master
            docker build -t $IMAGE_NAME:latest .

      - run:
          name: Docker login
          command: echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USER --password-stdin

      - run:
          name: Docker push
          command: docker push $IMAGE_NAME:latest

  deploy-nomad:
    executor: deploy-executor
    steps:
      - checkout

      - run:
          name: Install curl and unzip, download Nomad binary
          command: |
            apk add --no-cache curl unzip
            curl -LO https://releases.hashicorp.com/nomad/1.9.7/nomad_1.9.7_linux_amd64.zip
            unzip nomad_1.9.7_linux_amd64.zip

      - run:
          name: Show Nomad version
          command: ./nomad version

      - run:
          name: Convert .nomad to JSON
          command: |
            ./nomad job run -output $NOMAD_JOB_FILE > parsed-job.json

      - run:
          name: Show parsed job
          command: cat parsed-job.json

      - run:
          name: Deploy parsed job to Nomad
          command: |
            curl -X POST "$NOMAD_ADDR/v1/jobs" \
              -H "Content-Type: application/json" \
              --data-binary @parsed-job.json

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push
      - deploy-nomad:
          requires:
            - build-and-push
