version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_NAME: ghcr.io/berkaydedeoglu/reverse-proxy-master

  deploy-executor:
    docker:
      - image: alpine:latest  # Küçük, hızlı, güvenli
    environment:
      NOMAD_JOB_FILE: reverse-proxy-master/reverse-proxy-master.nomad
    working_directory: ~/project

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Docker build
          command: |
            cd reverse-proxy-master
            docker build -t $IMAGE_NAME:latest .

      - run:
          name: Docker login
          command: echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USER --password-stdin

      - run:
          name: Docker push
          command: docker push $IMAGE_NAME:latest

  deploy-nomad:
    executor: deploy-executor
    steps:
      - checkout

      - run:
          name: Install curl and jq
          command: apk add --no-cache curl jq

      - run:
          name: Print raw API response (debug)
          command: |
            curl -i -X POST "$NOMAD_ADDR/v1/jobs/parse?region=global&canonicalize=true&validate=true" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @$NOMAD_JOB_FILE
      - run:
          name: Parse HCL with Nomad API
          command: |
            echo "Parsing job file..."
            curl -s -X POST "$NOMAD_ADDR/v1/jobs/parse?region=global&canonicalize=true&validate=true" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @$NOMAD_JOB_FILE \
              -o parsed-job.json

            echo "Parsed job:"
            cat parsed-job.json | jq '.'

      - run:
          name: Deploy parsed job to Nomad
          command: |
            echo "Deploying job to $NOMAD_ADDR..."
            curl -X POST "$NOMAD_ADDR/v1/jobs" \
              -H "Content-Type: application/json" \
              --data-binary @parsed-job.json

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push
      - deploy-nomad:
          requires:
            - build-and-push
