version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_NAME: ghcr.io/berkaydedeoglu/reverse-proxy-master
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Docker build
          command: |
            cd reverse-proxy-master
            docker build -t $IMAGE_NAME:latest .

      - run:
          name: Docker login to GHCR
          command: echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USER --password-stdin

      - run:
          name: Push image
          command: docker push $IMAGE_NAME:latest

workflows:
  build:
    jobs:
      - build-and-push
